[package]
name = "buf-read-ext"
version = "0.2.0"
description = "Trait extending anything that implements BufRead with stream_until_token()"
authors = ["Mike Dilger <mike@optcomp.nz>"]
readme = "README.md"
repository = "https://github.com/mikedilger/buf-read-ext"
documentation = "https://mikedilger.github.io/buf-read-ext"
license = "MIT OR Apache-2.0"

[dependencies]
memchr = "0.1"
